"""add claimed by user to donations

Revision ID: 27ae2c925b6a
Revises: 80e5b5de923c
Create Date: 2026-08-10 20:29:35.654774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ae2c925b6a'
down_revision: Union[str, Sequence[str], None] = '80e5b5de923c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('claimed_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'donations', 'users', ['claimed_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_column('donations', 'claimed_by_user_id')
    # ### end Alembic commands ###
