"""make ngo user id unique

Revision ID: cd3e9c9c47e3
Revises: e1bffc9b1d41
Create Date: 2026-08-11 01:30:58.124319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3e9c9c47e3'
down_revision: Union[str, Sequence[str], None] = 'e1bffc9b1d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ngos', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ngos', type_='unique')
    # ### end Alembic commands ###
