"""add ngo verification details

Revision ID: e1bffc9b1d41
Revises: 51040bcd3610
Create Date: 2026-08-10 23:06:49.755293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bffc9b1d41'
down_revision: Union[str, Sequence[str], None] = '51040bcd3610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('address', sa.String(), nullable=True))
    op.add_column('verification_requests', sa.Column('city', sa.String(), nullable=True))
    op.add_column('verification_requests', sa.Column('state', sa.String(), nullable=True))
    op.add_column('verification_requests', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('verification_requests', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('verification_requests', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('verification_requests', 'organization_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('verification_requests', 'registration_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_requests', 'registration_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('verification_requests', 'organization_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('verification_requests', 'description')
    op.drop_column('verification_requests', 'longitude')
    op.drop_column('verification_requests', 'latitude')
    op.drop_column('verification_requests', 'state')
    op.drop_column('verification_requests', 'city')
    op.drop_column('verification_requests', 'address')
    # ### end Alembic commands ###
